name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "6e011b49268542dc8ad495ee177aa4de" },
  { binding = "SHARE", id = "99be8d18bfef45a696f87ea29910ea34" }
]